version: "3.8"

services:
  backend:
    image: bryann444/tfe_backend:latest
    deploy:
      replicas: 2
    networks:
      - tfe_net

  frontend:
    image: bryann444/tfe_frontend:latest
    deploy:
      replicas: 2
    networks:
      - tfe_net

  balanceador:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - /opt/tfe/nginx.conf:/etc/nginx/nginx.conf:ro
    deploy:
      replicas: 1
    networks:
      - tfe_net

networks:
  tfe_net:
    driver: overlay
